### ISSUE TITLE
Update to Syntax 0.6

### ISSUE THREAD

**Issue by stasm** [blushingpenguin/Fluent.Net#1]
Hey, thanks for implementing Fluent in C#!

We just published a new version of the Syntax specification: https://github.com/projectfluent/fluent/releases/tag/v0.6.0. The syntax stays mostly the same, but the underlying AST changes in a number of ways.

It would be great if `Fluent.Net` supported the 0.6 AST. I think it should be fairly easy to port the changes from the JS implementation. See https://github.com/projectfluent/fluent.js/pull/253.

**Comment by blushingpenguin** [comment]
I will take a look, thanks for letting me know about it

**Comment by blushingpenguin** [comment]
updates ported, thanks!
